# Generated by Django 2.0.7 on 2019-06-28 22:21

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=10)),
                ('active_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('frozen_time', models.DateTimeField(blank=True, null=True)),
                ('unfrozen_time', models.DateTimeField(blank=True, null=True)),
                ('deactivate_time', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, default='icpc.png', upload_to='')),
                ('is_public', models.BooleanField(default=True)),
                ('has_value', models.BooleanField(default=True)),
                ('enable', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ManyToManyField(blank=True, to='problem.Problem')),
                ('team', models.ManyToManyField(blank=True, to='authentication.Team')),
                ('user', models.ManyToManyField(blank=True, limit_choices_to={'role__short_name': 'team'}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together={('title', 'start_time', 'end_time')},
        ),
    ]
