
  # Generated by Django 2.0.7 on 2019-03-24 15:46

from django.db import migrations
from django.core.management import call_command

def loadfixture(app, schema_editor):
    call_command('loaddata', 'au_initial_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
    ]
