# Generated by Django 2.0.7 on 2019-06-28 19:53

from django.db import migrations
from django.core.management import call_command

def loadfixture(app, schema_editor):
    call_command('loaddata', 'com_initial_data.json')


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0002_auto_20190628_2223'),
    ]

    operations = [
    	migrations.RunPython(loadfixture),
    ]

